
services:

  rvms-vitepress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        IMAGE_MIRROR: ${IMAGE_MIRROR}
    ports:
      - "${RVMS_VITEPRESS_PORT:-8080}:80"
