ARG IMAGE_PREFIX

FROM ${IMAGE_PREFIX}node:latest AS builder

WORKDIR /app

COPY package.json package-lock.json ./
# 如果你用的是 npm，请使用下面两行中的一行（点击注释取消注释）
# RUN npm ci --registry=https://registry.npm.taobao.org
# 如果你用的是 yarn，请使用下面这一行
# RUN yarn install --frozen-lockfile
# 以下示例假设使用 npm：
RUN npm ci --verbose
# RUN npm instal --verbose

RUN npm ls

COPY . .

RUN npm run docs:build

RUN du -sh /app/docs/.vitepress/dist

FROM ${IMAGE_PREFIX}nginx:latest

COPY --from=builder /app/docs/.vitepress/dist /app